apiVersion: v1
kind: ConfigMap
metadata:
  name: azurefd-sim-nginx
  namespace: edge
data:
  nginx.conf: |
    worker_processes  1;
    events { worker_connections  1024; }

    http {
      access_log /var/log/nginx/access.log;
      error_log  /var/log/nginx/error.log;

      proxy_ssl_trusted_certificate /etc/nginx/ca/rootCA.crt;
      proxy_ssl_verify on;
      proxy_ssl_server_name on;

      server {
        listen              8443 ssl;
        server_name         localhost;

        ssl_certificate     /etc/nginx/tls/tls.crt;
        ssl_certificate_key /etc/nginx/tls/tls.key;

        location = /healthz {
          return 200 "ok\n";
        }

        location / {
          proxy_set_header Host localhost;
          proxy_set_header X-Forwarded-Proto https;
          proxy_set_header X-Forwarded-For $remote_addr;

          proxy_pass https://web-gw-dp.nginx-gateway.svc.cluster.local:443;

          proxy_ssl_name localhost;
        }
      }
    }
